python SBM_graph_eta.py --graphnum T1
python SBM_graph_eta.py --graphnum T2
python SBM_graph_eta.py --graphnum T3
python SBM_graph_eta.py --graphnum T4
python SBM_graph_eta.py --graphnum T5
python SBM_graph_eta.py --graphnum T6
python SBM_graph_eta.py --graphnum T7 
python SBM_graph_eta.py --graphnum T8 
python SBM_graph_eta.py --graphnum T9 

python SBM_graph_eta.py --graphnum TM1
python SBM_graph_eta.py --graphnum TM2
python SBM_graph_eta.py --graphnum TM3
python SBM_graph_eta.py --graphnum TM4
python SBM_graph_eta.py --graphnum TM5
python SBM_graph_eta.py --graphnum TM6
python SBM_graph_eta.py --graphnum TM7 
python SBM_graph_eta.py --graphnum TM8 
python SBM_graph_eta.py --graphnum TM9 

python SBM_graph_eta.py --graphnum TN1
python SBM_graph_eta.py --graphnum TN2
python SBM_graph_eta.py --graphnum TN3
python SBM_graph_eta.py --graphnum TN4
python SBM_graph_eta.py --graphnum TN5
python SBM_graph_eta.py --graphnum TN6
python SBM_graph_eta.py --graphnum TN7 
python SBM_graph_eta.py --graphnum TN8 
python SBM_graph_eta.py --graphnum TN9 

python SBM_graph_eta.py --graphnum TC1
python SBM_graph_eta.py --graphnum TC2
python SBM_graph_eta.py --graphnum TC3
python SBM_graph_eta.py --graphnum TC4
python SBM_graph_eta.py --graphnum TC5
python SBM_graph_eta.py --graphnum TC6
python SBM_graph_eta.py --graphnum TC7 
python SBM_graph_eta.py --graphnum TC8 
python SBM_graph_eta.py --graphnum TC9 

python SBM_graph_eta.py --graphnum TL1
python SBM_graph_eta.py --graphnum TL2
python SBM_graph_eta.py --graphnum TL3
python SBM_graph_eta.py --graphnum TL4
python SBM_graph_eta.py --graphnum TL5
python SBM_graph_eta.py --graphnum TL6
python SBM_graph_eta.py --graphnum TL7 
python SBM_graph_eta.py --graphnum TL8 
python SBM_graph_eta.py --graphnum TL9 

python SBM_graph_eta.py --graphnum TEST1
python SBM_graph_eta.py --graphnum TEST2
python SBM_graph_eta.py --graphnum TEST3
python SBM_graph_eta.py --graphnum TEST4
python SBM_graph_eta.py --graphnum TEST5
python SBM_graph_eta.py --graphnum TEST6
python SBM_graph_eta.py --graphnum TEST7 
python SBM_graph_eta.py --graphnum TEST8 
python SBM_graph_eta.py --graphnum TEST9 
